name: Docker Image Build

on:
  pull_request:
    branches:
      - "*"
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker image
        uses: actions/checkout@v3
        uses: docker/setup-buildx-action@v2
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: false
