name: Codecov

on:
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-C instrument-coverage"
  LLVM_PROFILE_FILE: "nomos-node-%p-%m.profraw"
  RISC0_DEV_MODE: true
  CONSENSUS_SLOT_TIME: 5
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    runs-on: ['ubuntu-latest']
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/prune-vm

      - uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: llvm-tools-preview

      - uses: cargo-bins/cargo-binstall@main

      - run: cargo binstall -y cargo-risczero && cargo risczero install

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all --no-default-features --features libp2p

      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --no-default-features --features libp2p

      - run: |
          cargo binstall -y grcov;
          mkdir /tmp/cov;
          grcov . --binary-path ./target/debug -s . -t lcov --branch --ignore-not-existing --ignore '../*' --ignore "/*" -o /tmp/cov/tests.lcov;

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: integration-test-artifacts
          path: tests/.tmp*

      - uses: codecov/codecov-action@v3
        with:
          directory: /tmp/cov/
          name: nomos-node-codecov
